name: Waka Readme

on:
  schedule:
    # 18:30 UTC daily (~10:30 AM PST / 12:00 AM IST)
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@6a2ec228c5ab57e173ac03586902a0b06b8f9301 # master as of 2026-05-09
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
